Feature/issue 136 verif
Medical-Information/medical-information-backend pull request #140
Opened 2023-07-26 15:52 UTC by StAndUP-ru

Добавил верификацию email + активацию пользователя

2023-07-26 16:04 UTC, ivan-varyukhin requested changes

2023-07-26 16:04 UTC, ivan-varyukhin commented on mailings/tasks.py
>                  'url': f'http://localhost:8000/api/v1/articles/{id__article}',
Раз уж ниже вынес в env, то стоит сразу и поменять

2023-07-26 16:32 UTC, StAndUP-ru commented on mailings/tasks.py
>                  'url': f'http://localhost:8000/api/v1/articles/{id__article}',
Эта правка под другой issue в другой ветке)

2023-07-26 16:35 UTC, ivan-varyukhin commented on mailings/tasks.py
>                  'url': f'http://localhost:8000/api/v1/articles/{id__article}',
ну ок

2023-07-26 16:35 UTC, ivan-varyukhin approved these changes

2023-07-27 10:09 UTC, GritsenkoSerge commented on stethoscope/settings.py
> +    'HIDE_USERS': False,
Из каких соображений тут стало False?
https://djoser.readthedocs.io/en/latest/settings.html#hide-users

2023-07-27 11:16 UTC, StAndUP-ru commented on stethoscope/settings.py
> +    'HIDE_USERS': False,
нам не потребуется фронту отдавать всех пользователей? GET на /users/ ?

2023-07-27 11:23 UTC, ivan-varyukhin commented on stethoscope/settings.py
> +    'HIDE_USERS': False,
нет. фронту все пользователи точно не нужны

2023-07-27 11:46 UTC, StAndUP-ru commented on stethoscope/settings.py
> +    'HIDE_USERS': False,
исправил

2023-07-27 11:53 UTC, GritsenkoSerge approved these changes

2023-07-27 11:54 UTC, merged