Test article
Medical-Information/medical-information-backend pull request #200
Opened 2023-08-06 20:36 UTC by AlexanderUp

Часть тестов для статей.
Проверен базовый функционал (создание статьи через апи, добавление в избранное, добавление лайка/дизлайка (на данный момент только от одного пользователя)).

Замечания: ограничить возможность добавления неопубликованной статьи в избранное, возможность ставить лайки\дизлайки статье, автором которой является данный пользователь.

2023-08-07 05:11 UTC, ivan-varyukhin approved these changes

2023-08-07 09:41 UTC, GritsenkoSerge requested changes
Круто, что взялся за тесты!
Есть пара замечаний.

2023-08-07 09:41 UTC, GritsenkoSerge commented on tests/test_users.py
если тут предполагаются только тесты с меткой django_db,  то лучше сделать ее на уровне модуля
https://docs.pytest.org/en/7.1.x/reference/reference.html?highlight=pytestmark#globalvar-pytestmark

2023-08-07 09:41 UTC, GritsenkoSerge commented on tests/test_articles.py
> +def test_article(authenticated_client, user, article_data):
Это плохая практика засовывать все в один тест.
Нужно разбить на как можно меньшие части.
Желательно придерживаться [AAA](https://jamescooke.info/arrange-act-assert-pattern-for-python-developers.html).

2023-08-08 11:31 UTC, AlexanderUp commented
Дописал тесты, поправил баги, отрефакторил.

2023-08-08 20:02 UTC, GritsenkoSerge requested changes

2023-08-08 20:02 UTC, GritsenkoSerge commented on api/views.py
>          return Response(
давай без get_object_or_404 тут обойдемся. а то нам опять ревьюер замечание выпишет

2023-08-08 21:40 UTC, GritsenkoSerge approved these changes

2023-08-08 21:40 UTC, merged