feat: add avatar field for user
Medical-Information/medical-information-backend pull request #225
Opened 2023-08-09 17:45 UTC by ivan-varyukhin

добавил юзеру поле аватарки

2023-08-09 18:10 UTC, AlexanderUp approved these changes

2023-08-10 07:53 UTC, GritsenkoSerge requested changes

2023-08-10 07:53 UTC, GritsenkoSerge commented on api/serializers.py
> +            'avatar',
suggestion: чуть выше надо добавить avatar = Base64ImageField()

2023-08-10 07:53 UTC, GritsenkoSerge commented on users/models.py
> +    avatar = models.ImageField(upload_to='images/', blank=True)
Давай в отдельную директорию их складывать будем. Пока не знаю зачем, но хуже не будет.
```suggestion
    avatar = models.ImageField(upload_to='avatars/', blank=True)
```

2023-08-10 08:32 UTC, GritsenkoSerge approved these changes

2023-08-10 08:32 UTC, merged