Сode review
Medical-Information/medical-information-backend pull request #89
Opened 2023-07-18 19:33 UTC by GritsenkoSerge

2023-07-19 22:09 UTC, ReznikovRoman requested changes
Хорошее начало, но еще стоит немного доработать проект

2023-07-19 22:09 UTC, ReznikovRoman commented on likes/services.py
> +def add_likedislike(obj, user, vote_type):
`likedislike` - тут все-таки советую более осмысленное название придумать :)

2023-07-19 22:09 UTC, ReznikovRoman commented on likes/services.py
> +    """Adds a like/dislike to an object"""
По правилам [pydocstyle](http://www.pydocstyle.org/en/stable/error_codes.html) докстринг должен заканчиваться точкой

Проверьте во всем проекте

2023-07-19 22:09 UTC, ReznikovRoman commented on likes/services.py
> +    """
Тут какой-то лишний перенос строки - основной докстринг должен помещаться на одну строчку

Проверьте во всем проекте

2023-07-19 22:09 UTC, ReznikovRoman commented on likes/services.py
> +def is_group(obj, user, vote_type=None) -> bool:
nit: Выше писал уже про глаголы в названиях функций/методов, но здесь еще стоит подумать над более осмысленными названиями. Или как минимум добавить аннотации к параметрами и возвращаемым значениям

Просто сейчас по названию функции (`remove_vote`, `get_group(obj, vote_group)`) не до конца понятно, что именно/как сделает функция/что нужно передать. Например, если вы хотите получить группу по ID связанной статьи, то логичнее назвать функцию как-нибудь вроде `get_group_by_article_id`

2023-07-19 22:09 UTC, ReznikovRoman commented on stethoscope/settings.py
> +    'users.apps.UsersConfig',
Порядок приложений в `INSTALLED_APPS` имеет большое значение, поэтому лучше располагать подключенные приложения примерно таким образом: приложения от Джанго, приложения от сторонних библиотек (некоторые библиотеки нужно подключать раньше стандартных приложений Джанго, но это будет описано в документации), свои собственные приложения

То есть в этом случае тебе просто надо опустить твои приложения ниже

2023-07-19 22:09 UTC, ReznikovRoman commented on tests/fixtures/fixture_user.py
> +import pytest
Тут как будто с сортировкой импортов что-то не то

2023-07-19 22:09 UTC, ReznikovRoman commented on users/services.py
> +def rating(user) -> int:
Тут аналогичная проблема с названиями функций, писал уже выше об этом

2023-07-20 09:16 UTC, ivan-varyukhin commented on articles/models.py
> +        # if not self.reading_time and self.text:
это вообще надо убирать вместе с соответствующим полем - расчет времени чтения будет делаться фронтом (дабы не захламлять базу)

2023-07-20 10:35 UTC, GritsenkoSerge commented on .github/workflows/workflow.yml
> +            sudo docker pull ${{ vars.DOCKER_USERNAME }}/stethoscope-backend
В прошлом был опыт проблем с кэшем образов.
Попробую сделать так и буду наблюдать.

2023-07-20 10:39 UTC, GritsenkoSerge commented on .github/workflows/workflow.yml
> +        python-version: ["3.10", "3.11"]
Злая шутка курсов по Python. Каждый раз ревьюеры требовали проверки на разных версиях, не объясняя зачем.
Оставляю 3.11

2023-07-20 10:40 UTC, GritsenkoSerge commented on .github/workflows/workflow.yml
> +            sudo docker compose up -d --build
Принято

2023-07-20 10:43 UTC, GritsenkoSerge commented on api/filters.py
> +    def filter_tags(self, queryset, name, value):  # noqa
Исправлено

2023-07-20 11:02 UTC, GritsenkoSerge commented on api/permissions.py
> +    """Allows access only for admins."""
Исправлено

2023-07-20 11:21 UTC, GritsenkoSerge commented on api/views.py
> +        article = get_object_or_404(Article, id=pk)
Заиспользовал количество удаленных и признак создания - стало меньше кода.
Тем не менее get_object_or_404(Article, id=pk) оставил, так как хочу разделять ситуации когда передали "левый" id пользователя (404) от невалидной для текущего состояния операции (400)

2023-07-20 11:28 UTC, GritsenkoSerge commented on api/serializers.py
> +        fields = '__all__'
сделано

2023-07-20 11:42 UTC, GritsenkoSerge commented on tests/fixtures/fixture_user.py
> +import pytest
как-будто все в порядке)
PEP8 не дает четких правил по сортировке импортов
если придерживаться, например, этого [стайлгайда](https://github.com/reddit-archive/reddit/wiki/PythonImportGuidelines), то все нормально

2023-07-20 11:46 UTC, GritsenkoSerge commented on articles/models.py
> +User = settings.AUTH_USER_MODEL
Джанго сам использует эту переменную в своих миграциях. Там не стал убирать. В остальных местах поменял на get_user_model()

2023-07-20 11:49 UTC, GritsenkoSerge commented on articles/models.py
> +        # if not self.reading_time and self.text:
убрал

2023-07-20 12:15 UTC, GritsenkoSerge commented on articles/models.py
> +    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
указал

2023-07-20 12:16 UTC, GritsenkoSerge commented on articles/models.py
> +    """Избранная статья пользователя (закладка)."""
русский

2023-07-20 12:17 UTC, GritsenkoSerge commented on likes/managers.py
> +        return self.get_queryset().aggregate(Sum('vote')).get('vote__sum') or 0
убрал

2023-07-20 12:21 UTC, GritsenkoSerge commented on stethoscope/requirements/base.txt
> +Django==4.2.2
#96

2023-07-20 12:21 UTC, GritsenkoSerge commented on likes/services.py
> +def add_likedislike(obj, user, vote_type):
переименовал в add_vote

2023-07-20 12:22 UTC, GritsenkoSerge commented on likes/services.py
> +    """
исправил

2023-07-20 12:27 UTC, GritsenkoSerge commented on likes/services.py
> +def is_group(obj, user, vote_type=None) -> bool:
переименовал

2023-07-20 12:29 UTC, GritsenkoSerge commented on stethoscope/settings.py
> +    'users.apps.UsersConfig',
сделано

2023-07-20 12:34 UTC, GritsenkoSerge commented on likes/managers.py
> +    def likes(self):
#97

2023-07-20 12:36 UTC, GritsenkoSerge commented on likes/models.py
> +    VOTES = (
#97

2023-07-20 12:41 UTC, GritsenkoSerge commented on users/services.py
> +def rating(user) -> int:
добавил глагол

2023-07-20 12:47 UTC, GritsenkoSerge commented on api/views.py
> +        qs = Article.objects.all()
Заджойнил. Но там еще надо убрать лишнее из запроса. Это мы сделаем в рамках оптимизации запросов. #72

2023-07-20 12:50 UTC, GritsenkoSerge commented on articles/models.py
> +    @property
решили перенести эту логику на фронт (именно reading_time)
по остальным пройдемся в рамках оптимизации запросов #72

2023-07-23 21:47 UTC, GritsenkoSerge commented on stethoscope/requirements/base.txt
> +django-cors-headers==4.2.0
лишняя строка
```suggestion
django-cors-headers==4.2.0
```

2023-07-28 19:01 UTC, ReznikovRoman requested changes
Есть несколько советов по доработке проекта

2023-07-29 12:47 UTC, GritsenkoSerge commented on api/views.py
> +        get_object_or_404(Article, id=pk)
> Не нужно просто так вызывать метод get_object_or_404, для проверки существования сущности есть метод `.exists`
> 
> Но вообще тут можно и без этой проверки обойтись (если вам не требуется это по ТЗ)
> 
> Проверьте во всем проекте (выше еще видел такое)

Роман, давай представим, что фронт передал неправильный id статьи. Что будет без get_object_or_404? Правильно, ничего. Он даже не узнает, что что-то сделал не так. Можно, конечно, и exists использовать, будет две строки вместо одной и чуть легче запрос к БД.

2023-08-10 08:54 UTC, closed without merging